# Generated by Django 5.0.2 on 2024-03-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bestTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('month', models.CharField(max_length=15)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
