# Generated by Django 5.0.2 on 2024-03-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travello', '0002_besttrips_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('Price', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
