# Generated by Django 5.0.2 on 2024-03-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travello', '0005_alldestinations_delete_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldestinations',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
