# Generated by Django 5.0.2 on 2024-03-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travello', '0006_alldestinations_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=150)),
                ('Message', models.TextField()),
            ],
        ),
    ]
