# Generated by Django 5.0.2 on 2024-03-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travello', '0007_userfeedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bestTrips',
            new_name='News',
        ),
    ]
